# Generated by Django 4.2.17 on 2025-01-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "proposals",
            "0002_proposal_days_required_alter_proposal_description_and_more",
        ),
        ("jobs", "0002_job_days_required_job_rate_alter_job_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposals.proposal",
                    ),
                ),
            ],
        ),
    ]
